// <auto-generated />
using System;
using HopewellClinicApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HopewellClinicApi.Migrations
{
    [DbContext(typeof(HopewellDbContext))]
    [Migration("20251007194912_AddAppointmentIndexes")]
    partial class AddAppointmentIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HopewellClinicApi.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655449001"),
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655449002"),
                            Name = "doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655449003"),
                            Name = "nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655449004"),
                            Name = "patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("HopewellClinicApi.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655441001"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "26c44625-2372-4692-a0cd-db78a2064958",
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3012),
                            Email = "nomsa.mandela@hopewell.com",
                            EmailConfirmed = true,
                            FirstName = "Dr. Nomsa",
                            IsActive = true,
                            LastName = "Mandela",
                            LockoutEnabled = false,
                            NormalizedEmail = "NOMSA.MANDELA@HOPEWELL.COM",
                            NormalizedUserName = "NOMSA.MANDELA@HOPEWELL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBLC+82KkL8Zl2E1f4aXkXwzWf6a/b8b/eXwzWf6a/b8b/eXwzWf6a/b8b/eQ==",
                            PhoneNumber = "+27123456789",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3017),
                            UserName = "nomsa.mandela@hopewell.com"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655441003"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b38d2416-3fa2-48fc-9026-5cefc994aeed",
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3114),
                            Email = "thabo.sithole@hopewell.com",
                            EmailConfirmed = true,
                            FirstName = "Dr. Thabo",
                            IsActive = true,
                            LastName = "Sithole",
                            LockoutEnabled = false,
                            NormalizedEmail = "THABO.SITHOLE@HOPEWELL.COM",
                            NormalizedUserName = "THABO.SITHOLE@HOPEWELL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBLC+82KkL8Zl2E1f4aXkXwzWf6a/b8b/eXwzWf6a/b8b/eXwzWf6a/b8b/eQ==",
                            PhoneNumber = "+27123456790",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3115),
                            UserName = "thabo.sithole@hopewell.com"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655441004"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f08722f-b053-4255-a4f7-54ead42af25b",
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4527),
                            Email = "john.doe@test.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@TEST.COM",
                            NormalizedUserName = "JOHN.DOE@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBLC+82KkL8Zl2E1f4aXkXwzWf6a/b8b/eXwzWf6a/b8b/eXwzWf6a/b8b/eQ==",
                            PhoneNumber = "+27123456791",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4528),
                            UserName = "john.doe@test.com"
                        });
                });

            modelBuilder.Entity("HopewellClinicApi.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("date")
                        .HasColumnName("appointment_date");

                    b.Property<string>("ApprovalNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("approval_notes");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int")
                        .HasColumnName("approval_status");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("approved_by");

                    b.Property<string>("ApprovedByNurseId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("approved_by_nurse_id");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("booking_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsWalkIn")
                        .HasColumnType("bit")
                        .HasColumnName("is_walkin");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("NurseApprovalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("nurse_approval_date");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_status");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_id");

                    b.Property<decimal?>("ServicePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("service_price");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("staff_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("HopewellClinicApi.Models.DoctorSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("BreakEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("BreakStart")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("ShiftEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ShiftStart")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "DayOfWeek", "Date")
                        .IsUnique();

                    b.ToTable("DoctorSchedules");
                });

            modelBuilder.Entity("HopewellClinicApi.Models.DoctorShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("day_of_week");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("doctor_shifts");
                });

            modelBuilder.Entity("HopewellClinicApi.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("PatientNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("patient_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PatientNumber")
                        .IsUnique()
                        .HasFilter("[patient_number] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("HopewellClinicApi.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3654),
                            Description = "General medical consultation and examination",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "General Consultation",
                            UpdatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3655)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3676),
                            Description = "Health services for infants and children",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Pediatrics Consultation",
                            UpdatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3677)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440002"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3687),
                            Description = "Routine dental examination and cleaning",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Dental Checkup",
                            UpdatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3688)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440003"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3697),
                            Description = "Physical therapy for rehabilitation",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Physiotherapy Session",
                            UpdatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3699)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440004"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3708),
                            Description = "Routine immunizations and boosters",
                            DurationMinutes = 20,
                            IsActive = true,
                            Name = "Vaccination",
                            UpdatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3710)
                        });
                });

            modelBuilder.Entity("HopewellClinicApi.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("StaffNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("staff_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StaffNumber")
                        .IsUnique()
                        .HasFilter("[staff_number] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("staff");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655441000"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3906),
                            IsActive = true,
                            StaffNumber = "DOC001",
                            UpdatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3908),
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655441001")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655441002"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3922),
                            IsActive = true,
                            StaffNumber = "DOC002",
                            UpdatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(3923),
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655441003")
                        });
                });

            modelBuilder.Entity("HopewellClinicApi.Models.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("day_of_week");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.ToTable("time_slots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443101"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4105),
                            DayOfWeek = 1,
                            Duration = 30,
                            EndTime = new TimeOnly(10, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443102"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4122),
                            DayOfWeek = 1,
                            Duration = 30,
                            EndTime = new TimeOnly(11, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443103"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4131),
                            DayOfWeek = 1,
                            Duration = 30,
                            EndTime = new TimeOnly(12, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443201"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4140),
                            DayOfWeek = 2,
                            Duration = 30,
                            EndTime = new TimeOnly(10, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443202"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4148),
                            DayOfWeek = 2,
                            Duration = 30,
                            EndTime = new TimeOnly(11, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443203"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4157),
                            DayOfWeek = 2,
                            Duration = 30,
                            EndTime = new TimeOnly(12, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443301"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4175),
                            DayOfWeek = 3,
                            Duration = 30,
                            EndTime = new TimeOnly(10, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443302"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4183),
                            DayOfWeek = 3,
                            Duration = 30,
                            EndTime = new TimeOnly(11, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443303"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4191),
                            DayOfWeek = 3,
                            Duration = 30,
                            EndTime = new TimeOnly(12, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443401"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4200),
                            DayOfWeek = 4,
                            Duration = 30,
                            EndTime = new TimeOnly(10, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443402"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4208),
                            DayOfWeek = 4,
                            Duration = 30,
                            EndTime = new TimeOnly(11, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443403"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4233),
                            DayOfWeek = 4,
                            Duration = 30,
                            EndTime = new TimeOnly(12, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443501"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4242),
                            DayOfWeek = 5,
                            Duration = 30,
                            EndTime = new TimeOnly(10, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443502"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4251),
                            DayOfWeek = 5,
                            Duration = 30,
                            EndTime = new TimeOnly(11, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655443503"),
                            CreatedAt = new DateTime(2025, 10, 7, 19, 49, 10, 148, DateTimeKind.Utc).AddTicks(4423),
                            DayOfWeek = 5,
                            Duration = 30,
                            EndTime = new TimeOnly(12, 0, 0),
                            IsActive = true,
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeOnly(11, 0, 0)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655441001"),
                            RoleId = new Guid("550e8400-e29b-41d4-a716-446655449002")
                        },
                        new
                        {
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655441003"),
                            RoleId = new Guid("550e8400-e29b-41d4-a716-446655449002")
                        },
                        new
                        {
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655441004"),
                            RoleId = new Guid("550e8400-e29b-41d4-a716-446655449004")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HopewellClinicApi.Models.Appointment", b =>
                {
                    b.HasOne("HopewellClinicApi.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HopewellClinicApi.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HopewellClinicApi.Models.Staff", "Staff")
                        .WithMany("Appointments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("HopewellClinicApi.Models.DoctorSchedule", b =>
                {
                    b.HasOne("HopewellClinicApi.Models.Staff", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HopewellClinicApi.Models.DoctorShift", b =>
                {
                    b.HasOne("HopewellClinicApi.Models.ApplicationUser", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HopewellClinicApi.Models.Patient", b =>
                {
                    b.HasOne("HopewellClinicApi.Models.ApplicationUser", "User")
                        .WithOne("Patient")
                        .HasForeignKey("HopewellClinicApi.Models.Patient", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HopewellClinicApi.Models.Staff", b =>
                {
                    b.HasOne("HopewellClinicApi.Models.ApplicationUser", "User")
                        .WithOne("Staff")
                        .HasForeignKey("HopewellClinicApi.Models.Staff", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HopewellClinicApi.Models.TimeSlot", b =>
                {
                    b.HasOne("HopewellClinicApi.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("HopewellClinicApi.Models.Staff", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("HopewellClinicApi.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HopewellClinicApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HopewellClinicApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("HopewellClinicApi.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HopewellClinicApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HopewellClinicApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HopewellClinicApi.Models.ApplicationUser", b =>
                {
                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("HopewellClinicApi.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HopewellClinicApi.Models.Service", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HopewellClinicApi.Models.Staff", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
